namespace XamlToolkit.Labs.WinUI
{
    runtimeclass OpacityMaskView : Microsoft.UI.Xaml.Controls.ContentControl
    {
        OpacityMaskView();
        Microsoft.UI.Xaml.UIElement OpacityMask;
        Microsoft.UI.Xaml.DependencyProperty OpacityMaskProperty{ get; };
    }
}
