namespace XamlToolkit.Labs.WinUI
{
    [webhosthidden]
    runtimeclass OpacityMaskView : Microsoft.UI.Xaml.Controls.ContentControl
    {
        OpacityMaskView();

        Microsoft.UI.Xaml.UIElement OpacityMask;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty OpacityMaskProperty{ get; };
    }
}
