namespace XamlToolkit.Labs.WinUI
{
    static runtimeclass NavigationViewItemAttach
    {

		static Microsoft.UI.Xaml.DependencyProperty SelectedIconProperty { get; };
		static Object GetSelectedIcon(Microsoft.UI.Xaml.DependencyObject obj);
		static void SetSelectedIcon(Microsoft.UI.Xaml.DependencyObject obj, Object value);

		static Microsoft.UI.Xaml.DependencyProperty ShowNotificationDotProperty { get; };
		static Boolean GetShowNotificationDot(Microsoft.UI.Xaml.DependencyObject obj);
		static void SetShowNotificationDot(Microsoft.UI.Xaml.DependencyObject obj, Boolean value);

		static Microsoft.UI.Xaml.DependencyProperty UnselectedIconProperty { get; };
		static Object GetUnselectedIcon(Microsoft.UI.Xaml.DependencyObject obj);
		static void SetUnselectedIcon(Microsoft.UI.Xaml.DependencyObject obj, Object value);

		static Microsoft.UI.Xaml.DependencyProperty StaticIconVisibilityProperty { get; };
		static Microsoft.UI.Xaml.Visibility GetStaticIconVisibility(Microsoft.UI.Xaml.DependencyObject obj);
		static void SetStaticIconVisibility(Microsoft.UI.Xaml.DependencyObject obj, Microsoft.UI.Xaml.Visibility value);
    }
}
