namespace XamlToolkit.WinUI
{
    runtimeclass SurfaceDialOptions : Microsoft.UI.Xaml.DependencyObject
    {
        SurfaceDialOptions();

        Windows.UI.Input.RadialControllerMenuKnownIcon Icon;
        Double StepValue;
        Boolean EnableHapticFeedback;
        Double RotationResolutionInDegrees;
        Double MinValue;
        Double MaxValue;
        Boolean EnableTapToNextControl;
        Boolean EnableMinMaxValue;

        static SurfaceDialOptions Default{ get; };
    };
}
