namespace XamlToolkit.Labs.WinUI
{
    enum MarqueeBehavior
    {
        Ticker,
        Looping,
        Bouncing,
    };

    enum MarqueeDirection
    {
        Left,
        Right,
        Up,
        Down,
    };

    runtimeclass Marquee : Microsoft.UI.Xaml.Controls.ContentControl
    {
        Marquee();

        void StartMarquee();

        void RestartMarquee();

        void ResumeMarquee();

        void PauseMarquee();

        void StopMarquee();

        event Windows.Foundation.TypedEventHandler<Marquee, Object> MarqueeStarted;

        event Windows.Foundation.TypedEventHandler<Marquee, Object> MarqueeStopped;

        event Windows.Foundation.TypedEventHandler<Marquee, Object> MarqueeResumed;

        event Windows.Foundation.TypedEventHandler<Marquee, Object> MarqueePaused;

        event Windows.Foundation.TypedEventHandler<Marquee, Object> MarqueeCompleted;

        Boolean AutoPlay;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty AutoPlayProperty{ get; };

        Double Speed;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty SpeedProperty{ get; };

        Microsoft.UI.Xaml.Media.Animation.RepeatBehavior RepeatBehavior;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty RepeatBehaviorProperty{ get; };

        MarqueeBehavior Behavior;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty BehaviorProperty{ get; };

        MarqueeDirection Direction;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty DirectionProperty{ get; };
    }
}
