// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

import "Effects/Abstract/PipelineEffect.idl";

namespace XamlToolkit.WinUI.Media
{
    /// <summary>
    /// An exposure effect
    /// </summary>
    /// <remarks>This effect maps to the Win2D ExposureEffect effect</remarks>
    [webhosthidden]
    runtimeclass ExposureEffect : PipelineEffect
    {
        /// <summary>
        /// Initializes a new instance of the ExposureEffect class.
        /// </summary>
        ExposureEffect();

        /// <summary>
        /// Gets or sets the amount of exposure to apply to the background (defaults to 0, should be in the [-2, 2] range).
        /// </summary>
        [noexcept]
        Double Amount;
    };
}
