// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

import "Effects/Abstract/PipelineEffect.idl";

namespace XamlToolkit.WinUI.Media
{
    /// <summary>
    /// A grayscale effect
    /// </summary>
    /// <remarks>This effect maps to the Win2D GrayscaleEffect effect</remarks>
    [webhosthidden]
	[default_interface]
    runtimeclass GrayscaleEffect : PipelineEffect
    {
        /// <summary>
        /// Initializes a new instance of the GrayscaleEffect class.
        /// </summary>
        GrayscaleEffect();
    };
}
