namespace XamlToolkit.WinUI.Behaviors
{
    /// <summary>
    /// This behavior automatically selects the entire content of the associated TextBox when it is loaded.
    /// </summary>
    [webhosthidden]
    runtimeclass AutoSelectBehavior : Microsoft.UI.Xaml.DependencyObject, [default] XamlToolkit.WinUI.Interactivity.IBehavior
    {
        AutoSelectBehavior();
    }
}
