<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
		<UseWinUI>true</UseWinUI>
		<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
	</PropertyGroup>

	<PropertyGroup>
		<CsWinRTIncludes>XamlToolkit.WinUI.Controls</CsWinRTIncludes>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.CsWinRT" />
		<PackageReference Include="Microsoft.WindowsAppSDK.WinUI" />
		<PackageReference Include="Microsoft.Graphics.Win2D" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\XamlToolkit.WinUI.Controls\XamlToolkit.WinUI.Controls.vcxproj" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\XamlToolkit.WinUI.Converters\XamlToolkit.WinUI.Converters.Interop.csproj" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\XamlToolkit.WinUI.Helpers\XamlToolkit.WinUI.Helpers.Interop.csproj" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\XamlToolkit.WinUI\XamlToolkit.WinUI.Interop.csproj" ReferenceOutputAssembly="false" />
	</ItemGroup>
</Project>