import "TransitionHelper/TransitionHelper.idl";

namespace XamlToolkit.Labs.WinUI
{
    runtimeclass StartTransitionAction : Microsoft.UI.Xaml.DependencyObject, XamlToolkit.WinUI.Interactivity.IAction
    {
        StartTransitionAction();

        static Microsoft.UI.Xaml.DependencyProperty TransitionProperty{ get; };
        TransitionHelper Transition;

        static Microsoft.UI.Xaml.DependencyProperty SourceProperty{ get; };
        Microsoft.UI.Xaml.FrameworkElement Source;

        static Microsoft.UI.Xaml.DependencyProperty TargetProperty{ get; };
        Microsoft.UI.Xaml.FrameworkElement Target;
    }
}
