import "Xaml/Abstract/KeyFrame.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A KeyFrame type for color animations.
    /// </summary>
    [webhosthidden]
    runtimeclass ColorKeyFrame : KeyFrame
    {
        ColorKeyFrame();

        /// <summary>
        /// Gets or sets the value for the keyframe.
        /// </summary>
        Windows.Foundation.IReference<Windows.UI.Color> Value;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };
    }
}
