import "Xaml/Abstract/KeyFrame.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A scalar keyframe.
    /// </summary>
    runtimeclass ScalarKeyFrame : KeyFrame
    {
        ScalarKeyFrame();

        Windows.Foundation.IReference<Double> Value;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };
    }
}
