import "Xaml/Abstract/KeyFrame.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A vector3 keyframe.
    /// </summary>
    [webhosthidden]
    runtimeclass Vector3KeyFrame : KeyFrame
    {
        Vector3KeyFrame();

        String Value;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };
    }
}
