namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// An interface representing a XAML model for a custom activity or action within an AnimationSet.
    /// </summary>
    [webhosthidden]
    interface IActivity
    {
        /// <summary>
        /// Invokes the current activity.
        /// </summary>
        /// <param name="element">The target UIElement to invoke the activity for.</param>
        /// <returns>An async action that indicates when the activity has completed its execution.</returns>
        Windows.Foundation.IAsyncAction InvokeAsync(Microsoft.UI.Xaml.UIElement element);
    };
}
