<?xml version="1.0" encoding="utf-8"?>
<Project>
    <Import Project="$(MSBuildThisFileDirectory)HybridCRT.props" />
    
    <PropertyGroup>
		<PlatformToolset>v145</PlatformToolset>
		<UseCrtSDKReference>false</UseCrtSDKReference>
        <UseCrtSDKReferenceStaticWarning>false</UseCrtSDKReferenceStaticWarning>
    </PropertyGroup>

	<ItemDefinitionGroup>
		<ClCompile>
			<LanguageStandard>stdcpp23</LanguageStandard>
		</ClCompile>
	</ItemDefinitionGroup>
</Project>