namespace XamlToolkit.WinUI.Controls
{
    [default_interface]
    runtimeclass AccentColorConverter : Microsoft.UI.Xaml.Data.IValueConverter
    {
        AccentColorConverter();

        [noexcept]
        static XamlToolkit.WinUI.HsvColor GetAccent(XamlToolkit.WinUI.HsvColor hsvColor, Int32 accentStep);
    }
}
