
namespace XamlToolkit.WinUI.Controls
{
	enum ColorChannel
	{
		Alpha,
		Channel1,
		Channel2,
		Channel3
	};

	enum ColorRepresentation
	{
		Hsva,
		Rgba
	};

	[webhosthidden]
	interface IColorPalette
	{
		Int32 ColorCount { get; };

		Int32 ShadeCount{ get; };

		Windows.UI.Color GetColor(Int32 colorIndex, Int32 shadeIndex);
	};

	[webhosthidden]
	runtimeclass ColorPicker : Microsoft.UI.Xaml.Controls.ColorPicker
	{
		ColorPicker();

		[noexcept]
		Windows.UI.Color CheckerBackgroundColor;

		Windows.Foundation.Collections.IObservableVector<Windows.UI.Color> CustomPaletteColors{ get; };

		Int32 CustomPaletteColumnCount;

		IColorPalette CustomPalette;

		Boolean IsColorPaletteVisible;

		Boolean ShowAccentColors;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty CustomPaletteColorsProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty CustomPaletteColumnCountProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty CustomPaletteProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty IsColorPaletteVisibleProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ShowAccentColorsProperty{ get; };
	}
}
