namespace XamlToolkit.WinUI.Controls
{
    [webhosthidden]
    [default_interface]
    runtimeclass NullToTransparentConverter : Microsoft.UI.Xaml.Data.IValueConverter
    {
        NullToTransparentConverter();
    }
}
