namespace XamlToolkit.Labs.WinUI
{
    runtimeclass Shimmer : Microsoft.UI.Xaml.Controls.Control
    {
        Shimmer();

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty DurationProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty IsActiveProperty{ get; };

        Windows.Foundation.TimeSpan Duration;

        Boolean IsActive;
    }
}
