namespace XamlToolkit.WinUI.Controls
{
    enum ThumbPosition
    {
        Top,
        Bottom,
        Left,
        Right,
        UpperLeft,
        UpperRight,
        LowerLeft,
        LowerRight
    };

    runtimeclass ImageCropperThumb : Microsoft.UI.Xaml.Controls.Control
    {
        ImageCropperThumb();
        Double X;
        Double Y;
        ThumbPosition Position;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty XProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty YProperty{ get; };
    }
}
