namespace XamlToolkit.Labs.WinUI
{
    runtimeclass LinkClickedEventArgs
    {
        LinkClickedEventArgs();
        LinkClickedEventArgs(Windows.Foundation.Uri uri);

        [noexcept]
        Windows.Foundation.Uri Uri { get; };

        [noexcept]
        Boolean Handled { get; set; };
    }
}
