import "MarkdownTextBlock/MarkdownThemes.idl";

namespace XamlToolkit.Labs.WinUI
{
    [webhosthidden]
    interface IImageProvider
    {
        Windows.Foundation.IAsyncOperation<Microsoft.UI.Xaml.Controls.Image> GetImage(String url);
        Boolean ShouldUseThisProvider(String url);
    }

    [webhosthidden]
    interface ISVGRenderer
    {
        Windows.Foundation.IAsyncOperation<Microsoft.UI.Xaml.Controls.Image> SvgToImage(String svgString);
    }

    [webhosthidden]
    runtimeclass MarkdownConfig 
    {
        MarkdownConfig();
        String BaseUrl{ get; set; };
        IImageProvider ImageProvider{ get; set; };
        ISVGRenderer SVGRenderer{ get; set; };
        MarkdownThemes Themes{ get; set; };

        static MarkdownConfig Default();
    }
}
