<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
		<NoWarn>$(NoWarn);CS0108;NU1701</NoWarn>
		<Win2DWarnNoPlatform>false</Win2DWarnNoPlatform>
		<UseWinUI>true</UseWinUI>
		<AssetTargetFallback>$(AssetTargetFallback);native</AssetTargetFallback>
		<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
	</PropertyGroup>

	<PropertyGroup>
		<CsWinRTIncludes>XamlToolkit.WinUI.Interactivity</CsWinRTIncludes>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.CsWinRT" />
		<PackageReference Include="Microsoft.WindowsAppSDK.WinUI" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\XamlToolkit.WinUI.Interactivity\XamlToolkit.WinUI.Interactivity.vcxproj" />
	</ItemGroup>
</Project>