namespace CommunityToolkit.WinUI.Converters
{
    [default_interface]
    runtimeclass ColorToDisplayNameConverter : Microsoft.UI.Xaml.Data.IValueConverter
    {
        ColorToDisplayNameConverter();
    }
}
