
namespace XamlToolkit.WinUI.Behaviors
{
    /// <summary>
    /// An IAction implementation that can trigger a target AnimationSet instance.
    /// </summary>
    [webhosthidden]
    runtimeclass StartAnimationAction : Microsoft.UI.Xaml.DependencyObject, XamlToolkit.WinUI.Interactivity.IAction
    {
        StartAnimationAction();

        /// <summary>
        /// Gets or sets the linked AnimationSet instance to invoke.
        /// </summary>
        XamlToolkit.WinUI.Animations.AnimationSet Animation;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty AnimationProperty { get; };

        /// <summary>
        /// Gets or sets the object to start the specified animation on. If not specified, will use the current object the parent animation is running on.
        /// </summary>
        Microsoft.UI.Xaml.UIElement TargetObject;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TargetObjectProperty { get; };
    }
}
