import "BoolToObjectConverter.idl";

namespace XamlToolkit.WinUI.Converters
{
    [webhosthidden]
    [default_interface]
    runtimeclass BoolToVisibilityConverter : BoolToObjectConverter
    {
        BoolToVisibilityConverter();
    }
}
