namespace XamlToolkit.WinUI.Converters
{
    [webhosthidden]
    unsealed runtimeclass BoolToObjectConverter : Microsoft.UI.Xaml.DependencyObject, Microsoft.UI.Xaml.Data.IValueConverter
    {
        BoolToObjectConverter();
   
        Object TrueValue;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TrueValueProperty{ get; };

        Object FalseValue;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty FalseValueProperty{ get; };
    }
}
