// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
import "EmptyCollectionToObjectConverter.idl";

namespace XamlToolkit.WinUI.Converters
{
    /// <summary>
    /// This class converts a collection size to visibility.
    /// </summary>
    [webhosthidden]
    [default_interface]
    runtimeclass CollectionVisibilityConverter : XamlToolkit.WinUI.Converters.EmptyCollectionToObjectConverter
    {
        CollectionVisibilityConverter();
    }
}
