// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
import "EmptyObjectToObjectConverter.idl";

namespace XamlToolkit.WinUI.Converters
{
    /// <summary>
    /// This class converts a collection size into an other object.
    /// Can be used to convert to bind a visibility, a color or an image to the size of the collection.
    /// </summary>
    [default_interface]
    unsealed runtimeclass EmptyCollectionToObjectConverter : XamlToolkit.WinUI.Converters.EmptyObjectToObjectConverter
    {
        EmptyCollectionToObjectConverter();
    }
}