// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

namespace XamlToolkit.WinUI.Converters
{
    /// <summary>
    /// Value converter that look up for the source string in the App Resources strings and returns its value, if found.
    /// </summary>
    [default_interface]
    runtimeclass ResourceNameToResourceStringConverter : Microsoft.UI.Xaml.Data.IValueConverter
    {
        ResourceNameToResourceStringConverter();
    }
}