// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

namespace XamlToolkit.WinUI.Converters
{
    /// <summary>
    /// This class provides a binding converter to display formatted strings.
    /// </summary>
    [default_interface]
    runtimeclass StringFormatConverter : Microsoft.UI.Xaml.Data.IValueConverter
    {
        StringFormatConverter();
    }
}