namespace XamlToolkit.WinUI.Controls
{
	runtimeclass UniformGrid : Microsoft.UI.Xaml.Controls.Grid
    {
        UniformGrid();

        Int32 Columns;
        Int32 FirstColumn;
        Microsoft.UI.Xaml.Controls.Orientation Orientation;
        Int32 Rows;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty AutoLayoutProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ColumnsProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty FirstColumnProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty OrientationProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty RowsProperty{ get; };

        [default_overload]
        static void SetAutoLayout(Microsoft.UI.Xaml.FrameworkElement element, Windows.Foundation.IReference<Boolean> value);

        [default_overload]
        static Windows.Foundation.IReference<Boolean> GetAutoLayout(Microsoft.UI.Xaml.FrameworkElement element);

        static void SetAutoLayout(Microsoft.UI.Xaml.Controls.RowDefinition element, Windows.Foundation.IReference<Boolean> value);
        static Windows.Foundation.IReference<Boolean> GetAutoLayout(Microsoft.UI.Xaml.Controls.RowDefinition element);

        static void SetAutoLayout(Microsoft.UI.Xaml.Controls.ColumnDefinition element, Windows.Foundation.IReference<Boolean> value);
        static Windows.Foundation.IReference<Boolean> GetAutoLayout(Microsoft.UI.Xaml.Controls.ColumnDefinition element);
    }
}
