namespace CommunityToolkit.WinUI.Controls.Primitives
{
    [default_interface]
    runtimeclass ColorPreviewer : Microsoft.UI.Xaml.Controls.Control
    {
        ColorPreviewer();

        CommunityToolkit.WinUI.HsvColor HsvColor;

        static Microsoft.UI.Xaml.DependencyProperty HsvColorProperty{ get; };

        Boolean ShowAccentColors;

        static Microsoft.UI.Xaml.DependencyProperty ShowAccentColorsProperty{ get; };

        event Windows.Foundation.EventHandler<CommunityToolkit.WinUI.HsvColor> ColorChangeRequested;
    }
}
