namespace CommunityToolkit.WinUI.Controls
{
    [bindable]
    [default_interface]
    runtimeclass ContrastBrushConverter : Microsoft.UI.Xaml.Data.IValueConverter
    {
        ContrastBrushConverter();
    }
}
