namespace XamlToolkit.WinUI.Controls
{
    [webhosthidden]
    [createfromstring("XamlToolkit.WinUI.Controls.AspectRatio.ConvertToAspectRatio")]
    runtimeclass AspectRatio : Windows.Foundation.IStringable
    {
        AspectRatio(Double width, Double height);

        AspectRatio(Double ratio);

        [noexcept]
        Double Width{ get; };

        [noexcept]
        Double Height{ get; };

        [noexcept]
        Double Value();

        static AspectRatio ConvertToAspectRatio(String rawString);
    }
}
