// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

import "Brushes/Base/XamlCompositionEffectBrushBase.idl";

namespace XamlToolkit.WinUI.Media
{
    /// <summary>
    /// A <see cref="XamlCompositionBrush"/> that implements an acrylic effect with customizable parameters
    /// </summary>
    runtimeclass AcrylicBrush : XamlCompositionEffectBrushBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AcrylicBrush"/> class.
        /// </summary>
        AcrylicBrush();

        /// <summary>
        /// Gets or sets the blur amount for the effect (must be a positive value)
        /// </summary>
        Double BlurAmount;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty BlurAmountProperty{ get; };

        /// <summary>
        /// Gets or sets the tint for the effect
        /// </summary>
        Windows.UI.Color TintColor;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TintColorProperty{ get; };

        /// <summary>
        /// Gets or sets the tint opacity factor for the effect (default is 0.5, must be in the [0, 1] range)
        /// </summary>
        Double TintOpacity;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TintOpacityProperty{ get; };

        /// <summary>
        /// Gets or sets the <see cref="Uri"/> for the texture to use
        /// </summary>
        Windows.Foundation.Uri TextureUri;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TextureUriProperty{ get; };
    };
}
