// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

import "Brushes/Base/XamlCompositionEffectBrushBase.idl";

namespace XamlToolkit.WinUI.Media
{
    /// <summary>
    /// Brush which applies a SaturationEffect to the Backdrop.
    /// </summary>
    runtimeclass BackdropSaturationBrush : XamlCompositionEffectBrushBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BackdropSaturationBrush"/> class.
        /// </summary>
        BackdropSaturationBrush();

        /// <summary>
        /// Gets or sets the saturation amount.
        /// </summary>
        Double Saturation;

        static Microsoft.UI.Xaml.DependencyProperty SaturationProperty{ get; };
    };
}