// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

import "Brushes/Base/XamlCompositionEffectBrushBase.idl";

namespace XamlToolkit.WinUI.Media
{
    /// <summary>
    /// Brush which applies a SepiaEffect to the Backdrop.
    /// </summary>
    runtimeclass BackdropSepiaBrush : XamlCompositionEffectBrushBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BackdropSepiaBrush"/> class.
        /// </summary>
        BackdropSepiaBrush();

        /// <summary>
        /// Gets or sets the intensity of the sepia effect.
        /// </summary>
        Double Intensity;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty IntensityProperty{ get; };
    };
}
