// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

import "Effects/Interfaces/IPipelineEffect.idl";
import "Pipelines/PipelineBuilder.idl";

namespace XamlToolkit.WinUI.Media
{
    /// <summary>
    /// A base pipeline effect.
    /// </summary>
    [webhosthidden]
	unsealed runtimeclass PipelineEffect : Microsoft.UI.Xaml.DependencyObject, IPipelineEffect
    {
        /// <summary>
        /// Initializes a new instance of the PipelineEffect class.
        /// </summary>
        PipelineEffect();

        /// <summary>
        /// Gets or sets a value indicating whether the effect can be animated.
        /// </summary>
        [noexcept]
        Boolean IsAnimatable;
    };
}
