// Wrapper for the XAML-generated XamlTypeInfo.g.cpp.
#include "pch.h"
#include "winrt_module_imports.h"

// Individual .h files whose implementation:: types are needed
// by XamlTypeInfo.g.cpp but not included by it directly.
#include "CameraPreview/CameraPreview.h"
#include "ColorPicker/ColorPicker.h"
#include "ColorPicker/ColorPickerButton.h"
#include "ColorPicker/ColorPickerSlider.h"
#include "ColorPicker/ColorPreviewer.h"
#include "SettingsControls/Helpers/CornerRadiusConverter.h"
#include "Segmented/EqualPanel.h"
#include "Sizers/GridSplitter/GridSplitter.h"
#include "HeaderedControls/HeaderedContentControl/HeaderedContentControl.h"
#include "HeaderedControls/HeaderedItemsControl/HeaderedItemsControl.h"
#include "HeaderedControls/HeaderedTreeView/HeaderedTreeView.h"
#include "ImageCropper/ImageCropper.h"
#include "ImageCropper/ImageCropperThumb.h"
#include "LayoutTransformControl/LayoutTransformControl.h"
#include "MetadataControl/MetadataControl.h"
#include "Sizers/PropertySizer/PropertySizer.h"
#include "RadialGauge/RadialGauge.h"
#include "RangeSelector/RangeSelector.h"
#include "RichSuggestBox/RichSuggestBox.h"
#include "Segmented/Segmented.h"
#include "Segmented/SegmentedItem.h"
#include "Segmented/SegmentedMarginConverter.h"
#include "SettingsControls/SettingsCard/SettingsCard.h"
#include "SettingsControls/SettingsExpander/SettingsExpander.h"
#include "SettingsControls/SettingsExpander/SettingsExpanderItemStyleSelector.h"
#include "Sizers/SizerBase.h"
#include "Sizers/ContentSizer/ContentSizer.h"
#include "TabbedCommandBar/TabbedCommandBar.h"
#include "TabbedCommandBar/TabbedCommandBarItem.h"
#include "TokenizingTextBox/TokenizingTextBox.h"
#include "TokenizingTextBox/TokenizingTextBoxItem.h"
#include "SettingsControls/SettingsCard/SettingsCardAutomationPeer.h"
#include "SettingsControls/SettingsExpander/SettingsExpanderAutomationPeer.h"
#include "Sizers/SizerAutomationPeer.h"

#if __has_include("Generated Files\\XamlTypeInfo.g.cpp")
#include "Generated Files\\XamlTypeInfo.g.cpp"
#endif