namespace XamlToolkit.WinUI.Behaviors
{
    /// <summary>
    /// A collection of FocusTarget.
    /// </summary>
    [default_interface]
    runtimeclass FocusTargetList : Microsoft.UI.Xaml.DependencyObjectCollection
    {
        FocusTargetList();
    }
}
