namespace XamlToolkit.WinUI.Helpers
{
    delegate void CompositionRenderingCallback();

    static runtimeclass CompositionTargetHelper
    {
        static Windows.Foundation.IAsyncOperation<Boolean>
            ExecuteAfterCompositionRenderingAsync(CompositionRenderingCallback callback);
    }
}
