namespace XamlToolkit.WinUI.Helpers
{
    [webhosthidden]
    static runtimeclass DesignTimeHelpers
    {
        static Boolean IsRunningInLegacyDesignerMode();

        static Boolean IsRunningInEnhancedDesignerMode();

        static Boolean IsRunningInApplicationRuntimeMode();
    }
}
