namespace XamlToolkit.WinUI.Helpers
{
    delegate void ThemeChangedHandler(ThemeListener sender);

    runtimeclass ThemeListener 
    {
        ThemeListener();
        ThemeListener(Microsoft.UI.Dispatching.DispatcherQueue dispatcherQueue);

        [noexcept]
        Microsoft.UI.Xaml.ApplicationTheme CurrentTheme{ get; };

        [noexcept]
        String CurrentThemeName{ get; };

        [noexcept]
        Boolean IsHighContrast{ get; };

        event ThemeChangedHandler ThemeChanged;
    }
}
