namespace XamlToolkit.WinUI.Helpers
{
    delegate void ThemeChangedHandler(ThemeListener sender);

    runtimeclass ThemeListener 
    {
        ThemeListener();
        ThemeListener(Microsoft.UI.Dispatching.DispatcherQueue dispatcherQueue);

        Microsoft.UI.Xaml.ApplicationTheme CurrentTheme{ get; };
        String CurrentThemeName{ get; };
        Boolean IsHighContrast{ get; };

        event ThemeChangedHandler ThemeChanged;
    }
}
