import "Xaml/AnimationDictionary.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// Attached properties to support explicitly triggered animations for UIElement instances.
    /// </summary>
    [webhosthidden]
    static runtimeclass Explicit
    {
        /// <summary>
        /// Gets the value of the AnimationsProperty property.
        /// </summary>
        static AnimationDictionary GetAnimations(Microsoft.UI.Xaml.UIElement element);

        /// <summary>
        /// Sets the value of the AnimationsProperty property.
        /// </summary>
        static void SetAnimations(Microsoft.UI.Xaml.UIElement element, AnimationDictionary value);

        /// <summary>
        /// Identifies the AnimationsProperty dependency property.
        /// </summary>

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty AnimationsProperty{ get; };
    }
}
