// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

import "Effects/Abstract/ImageSourceBaseExtension.idl";

namespace XamlToolkit.WinUI.Media
{
    /// <summary>
    /// An image effect, which displays an image loaded as a Win2D surface
    /// </summary>
    [default_interface]
    runtimeclass ImageSourceExtension : ImageSourceBaseExtension
    {
        /// <summary>
        /// Initializes a new instance of the ImageSourceExtension class.
        /// </summary>
        ImageSourceExtension();
    };
}