namespace XamlToolkit.Labs.WinUI
{
    [webhosthidden]
    [default_interface]
    runtimeclass AdornerLayer : Microsoft.UI.Xaml.Controls.Canvas
    {
        AdornerLayer();

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty XamlProperty{ get; };

        static Microsoft.UI.Xaml.UIElement GetXaml(Microsoft.UI.Xaml.FrameworkElement obj);

        static void SetXaml(Microsoft.UI.Xaml.FrameworkElement obj, Microsoft.UI.Xaml.UIElement value);

        static void RemoveAdorner(AdornerLayer layer, Microsoft.UI.Xaml.UIElement adornerXaml);

        static Windows.Foundation.IAsyncOperation<AdornerLayer> GetAdornerLayerAsync(Microsoft.UI.Xaml.FrameworkElement adornedElement);
    }
}
