import "Adorners/AdornerLayer.idl";

namespace XamlToolkit.Labs.WinUI
{
    [webhosthidden]
    unsealed runtimeclass Adorner : Microsoft.UI.Xaml.Controls.ContentControl
    {
        Adorner();

        [noexcept]
        overridable Microsoft.UI.Xaml.UIElement AdornedElement{ get; };

        [noexcept]
        AdornerLayer AdornerLayer{ get; set; };

        overridable void OnAttached();

        overridable void OnDetaching();

        void UpdateLayout();
    }
}
