import "Adorners/AdornerLayer.idl";

namespace XamlToolkit.Labs.WinUI
{
    [webhosthidden]
    [contentproperty("Child")]
    runtimeclass AdornerDecorator : Microsoft.UI.Xaml.Controls.Control
    {
        AdornerDecorator();

        Microsoft.UI.Xaml.UIElement Child{ get; set; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ChildProperty{ get; };

        AdornerLayer AdornerLayer{ get; };
    }
}
