namespace XamlToolkit.WinUI.Interactivity
{
    [webhosthidden]
    [default_interface]
    runtimeclass ActionCollection : Microsoft.UI.Xaml.DependencyObjectCollection
    {
        ActionCollection();
    }
}
