namespace XamlToolkit.WinUI.Interactivity
{
    [webhosthidden]
    static runtimeclass VisualStateUtilities
    {
        static Boolean GoToState(Microsoft.UI.Xaml.Controls.Control control, String stateName, Boolean useTransitions);

        static IVector<Microsoft.UI.Xaml.VisualStateGroup> GetVisualStateGroups(Microsoft.UI.Xaml.FrameworkElement element);

        static Microsoft.UI.Xaml.Controls.Control FindNearestStatefulControl(Microsoft.UI.Xaml.FrameworkElement element);
    }
}
