
namespace XamlToolkit.WinUI.Media
{
    enum InnerContentClipMode
    {
        None,
        CompositionMaskBrush,
        CompositionGeometricClip
    };

    runtimeclass AttachedCardShadow : XamlToolkit.WinUI.AttachedShadowBase
    {
        AttachedCardShadow();

        static Microsoft.UI.Xaml.DependencyProperty CornerRadiusProperty{ get; };

        static Microsoft.UI.Xaml.DependencyProperty InnerContentClipModeProperty{ get; };

        Double CornerRadius;
        InnerContentClipMode InnerContentClipMode;
    }
}
