
namespace XamlToolkit.WinUI.Media
{
    enum InnerContentClipMode
    {
        None,
        CompositionMaskBrush,
        CompositionGeometricClip
    };

    [webhosthidden]
    runtimeclass AttachedCardShadow : XamlToolkit.WinUI.AttachedShadowBase
    {
        AttachedCardShadow();

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty CornerRadiusProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty InnerContentClipModeProperty{ get; };

        Double CornerRadius;
        InnerContentClipMode InnerContentClipMode;
    }
}
