import "IAction.idl";

namespace XamlToolkit.WinUI.Interactivity
{
    enum ControlStoryboardOption
    {
        Play,
        Stop,
        TogglePlayPause,
        Pause,
        Resume,
        SkipToFill
    };

    [webhosthidden]
    runtimeclass ControlStoryboardAction : Microsoft.UI.Xaml.DependencyObject, XamlToolkit.WinUI.Interactivity.IAction
    {
        ControlStoryboardAction();

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ControlStoryboardOptionProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty StoryboardProperty{ get; };

        XamlToolkit.WinUI.Interactivity.ControlStoryboardOption ControlStoryboardOption;
        Microsoft.UI.Xaml.Media.Animation.Storyboard Storyboard;
    }
}
