namespace XamlToolkit.Labs.WinUI
{
    [default_interface]
    [createfromstring("XamlToolkit.Labs.WinUI.DoubleVector.CreateFromString")]
    runtimeclass DoubleVector : IVector<Double>
    {
        DoubleVector();

        DoubleVector(IIterable<Double> values);

        static DoubleVector CreateFromString(String value);
    }
}
