namespace XamlToolkit.Labs.WinUI
{
    [webhosthidden]
    [contentproperty("Content")]
    unsealed runtimeclass RibbonGroup : Microsoft.UI.Xaml.Controls.Control
    {
        RibbonGroup();

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ContentProperty{ get; };

        Microsoft.UI.Xaml.UIElement Content;

	    [noexcept]
	    static Microsoft.UI.Xaml.DependencyProperty LabelProperty{ get; };

        String Label;
    }
}
