// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

import "Visuals/PipelineVisualFactoryBase.idl";
import "Pipelines/PipelineBuilder.idl";
import "Effects/Interfaces/IPipelineEffect.idl";

namespace XamlToolkit.WinUI.Media
{
    /// <summary>
    /// A builder type for <see cref="SpriteVisual"/> instance to apply to UI elements.
    /// </summary>
    [webhosthidden]
    [contentproperty("Effects")]
    runtimeclass PipelineVisualFactory : PipelineVisualFactoryBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PipelineVisualFactory"/> class.
        /// </summary>
        PipelineVisualFactory();

        /// <summary>
        /// Gets or sets the source for the current pipeline (defaults to a <see cref="BackdropSourceExtension"/> with <see cref="AcrylicBackgroundSource.Backdrop"/> source).
        /// </summary>
	    [noexcept]
        XamlToolkit.WinUI.Media.Pipelines.PipelineBuilder Source;

        /// <summary>
        /// Gets or sets the collection of effects to use in the current pipeline.
        /// </summary>
        Windows.Foundation.Collections.IVector<IPipelineEffect> Effects;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty EffectsProperty{ get; };
    };
}
