namespace XamlToolkit.Labs.WinUI
{
    [webhosthidden]
    unsealed runtimeclass ColorSource : Microsoft.UI.Xaml.DependencyObject
    {
        ColorSource();

        event Windows.Foundation.EventHandler<Object> SourceUpdated;

        Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.IRandomAccessStream> GetPixelDataAsync(Int32 requestedSamples);
    }
}
