import "ColorAnalyzer/ColorSources/ColorSource.idl";

namespace XamlToolkit.Labs.WinUI
{
	[webhosthidden]
	runtimeclass StreamColorSource : ColorSource
    {
        StreamColorSource();

        Windows.Storage.Streams.IRandomAccessStream Source;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty SourceProperty{ get; };
    }
}
