import "ColorAnalyzer/ColorSources/ColorSource.idl";

namespace XamlToolkit.Labs.WinUI
{
    runtimeclass UIColorSource : ColorSource
    {
        UIColorSource();

        Microsoft.UI.Xaml.UIElement Source;

        static Microsoft.UI.Xaml.DependencyProperty SourceProperty{ get; };
    }
}
