import "Adorners/Adorner.idl";

namespace XamlToolkit.Labs.WinUI
{
    [webhosthidden]
    runtimeclass ResizeElementAdorner : Adorner
    {
        ResizeElementAdorner();

	    [noexcept]
        Microsoft.UI.Xaml.FrameworkElement AdornedElement{ get; };
    }
}
