import "RadialGauge/RadialGauge.idl";

namespace XamlToolkit.WinUI.Controls
{
    [webhosthidden]
    runtimeclass RadialGaugeAutomationPeer : Microsoft.UI.Xaml.Automation.Peers.RangeBaseAutomationPeer, Microsoft.UI.Xaml.Automation.Provider.IRangeValueProvider
    {
        RadialGaugeAutomationPeer(XamlToolkit.WinUI.Controls.RadialGauge owner);

        void RaiseValueChangedEvent(Double oldValue, Double newValue);
    }
}
