import "ColorAnalyzer/PaletteSelectors/ColorPaletteSelector.idl";

namespace XamlToolkit.Labs.WinUI
{
    [webhosthidden]
    [default_interface]
    runtimeclass ColorWeightPaletteSelector : ColorPaletteSelector
    {
        ColorWeightPaletteSelector();
    }
}
