namespace XamlToolkit.Labs.WinUI
{
    runtimeclass GradientSliderThumb : Microsoft.UI.Xaml.Controls.Control
    {
        GradientSliderThumb();

        Microsoft.UI.Xaml.Media.GradientStop GradientStop;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty GradientStopProperty{ get; };

        event Microsoft.UI.Xaml.Controls.Primitives.DragStartedEventHandler DragStarted;
        event Microsoft.UI.Xaml.Controls.Primitives.DragDeltaEventHandler DragDelta;
        event Microsoft.UI.Xaml.Controls.Primitives.DragCompletedEventHandler DragCompleted;
    }
}
