namespace CommunityToolkit.WinUI.Controls
{
    [default_interface]
    runtimeclass StyleExtensionResourceDictionary : Microsoft.UI.Xaml.ResourceDictionary
    {
        StyleExtensionResourceDictionary();
    }
}
