namespace XamlToolkit.WinUI
{
	[webhosthidden]
    static runtimeclass VisualExtensions 
    {
		static Microsoft.UI.Composition.Visual GetVisual(Microsoft.UI.Xaml.UIElement element);

		static String GetAnchorPoint(Microsoft.UI.Xaml.DependencyObject obj);

		static void SetAnchorPoint(Microsoft.UI.Xaml.DependencyObject obj, String value);

		static String GetCenterPoint(Microsoft.UI.Xaml.DependencyObject obj);

		static void SetCenterPoint(Microsoft.UI.Xaml.DependencyObject obj, String value);

		static String GetOffset(Microsoft.UI.Xaml.DependencyObject obj);

		static void SetOffset(Microsoft.UI.Xaml.DependencyObject obj, String value);

		static String GetTranslation(Microsoft.UI.Xaml.DependencyObject obj);

		static void SetTranslation(Microsoft.UI.Xaml.DependencyObject obj, String value);

		static Double GetOpacity(Microsoft.UI.Xaml.DependencyObject obj);

		static void SetOpacity(Microsoft.UI.Xaml.DependencyObject obj, Double value);

		static Double GetRotationAngle(Microsoft.UI.Xaml.DependencyObject obj);

		static void SetRotationAngle(Microsoft.UI.Xaml.DependencyObject obj, Double value);

		static Double GetRotationAngleInDegrees(Microsoft.UI.Xaml.DependencyObject obj);

		static void SetRotationAngleInDegrees(Microsoft.UI.Xaml.DependencyObject obj, Double value);

		static String GetRotationAxis(Microsoft.UI.Xaml.DependencyObject obj);

		static void SetRotationAxis(Microsoft.UI.Xaml.DependencyObject obj, String value);

		static String GetScale(Microsoft.UI.Xaml.DependencyObject obj);

		static void SetScale(Microsoft.UI.Xaml.DependencyObject obj, String value);

		static String GetSize(Microsoft.UI.Xaml.DependencyObject obj);

		static void SetSize(Microsoft.UI.Xaml.DependencyObject obj, String value);

		static String GetNormalizedCenterPoint(Microsoft.UI.Xaml.DependencyObject obj);

		static void SetNormalizedCenterPoint(Microsoft.UI.Xaml.DependencyObject obj, String value);

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty AnchorPointProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty CenterPointProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty OffsetProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty TranslationProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty OpacityProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty RotationAngleProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty RotationAngleInDegreesProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty RotationAxisProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ScaleProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty SizeProperty{ get; };

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty NormalizedCenterPointProperty{ get; };
    }
}
