import "Xaml/Abstract/Animation.idl";
import "Xaml/KeyFrames/ScalarKeyFrame.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A blur radius animation working on the composition layer.
    /// </summary>
    [contentproperty("KeyFrames")]
    runtimeclass BlurRadiusDropShadowAnimation : Animation
    {
        BlurRadiusDropShadowAnimation();

        XamlToolkit.WinUI.IAttachedShadow Target;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty TargetProperty{ get; };

        Windows.Foundation.IReference<Double> To;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ToProperty{ get; };

        Windows.Foundation.IReference<Double> From;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty FromProperty{ get; };

        Windows.Foundation.Collections.IVector<ScalarKeyFrame> KeyFrames;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty KeyFramesProperty{ get; };
    }
}
