import "Xaml/Abstract/Animation.idl";
import "Xaml/KeyFrames/ColorKeyFrame.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A color animation working on a DropShadow.
    /// </summary>
    [contentproperty("KeyFrames")]
    runtimeclass ColorDropShadowAnimation : Animation
    {
        ColorDropShadowAnimation();

        XamlToolkit.WinUI.IAttachedShadow Target;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty TargetProperty{ get; };

        Windows.Foundation.IReference<Windows.UI.Color> To;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ToProperty{ get; };

        Windows.Foundation.IReference<Windows.UI.Color> From;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty FromProperty{ get; };

        Windows.Foundation.Collections.IVector<ColorKeyFrame> KeyFrames;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty KeyFramesProperty{ get; };
    }
}
