import "Xaml/Abstract/Animation.idl";
import "Xaml/KeyFrames/Vector3KeyFrame.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// An offset animation working on a DropShadow.
    /// </summary>
    [contentproperty("KeyFrames")]
    runtimeclass OffsetDropShadowAnimation : Animation
    {
        OffsetDropShadowAnimation();

        XamlToolkit.WinUI.IAttachedShadow Target;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TargetProperty{ get; };

        String To;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ToProperty{ get; };

        String From;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty FromProperty{ get; };

        Windows.Foundation.Collections.IVector<Vector3KeyFrame> KeyFrames;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty KeyFramesProperty{ get; };
    }
}
