namespace XamlToolkit.WinUI.Controls
{
    [webhosthidden]
    runtimeclass TabbedCommandBarItemTemplateSelector : Microsoft.UI.Xaml.Controls.DataTemplateSelector
    {
        TabbedCommandBarItemTemplateSelector();

        [noexcept]
        Microsoft.UI.Xaml.DataTemplate Normal;

        [noexcept]
        Microsoft.UI.Xaml.DataTemplate Contextual;
    }
}
