namespace XamlToolkit.WinUI.Controls
{
    [webhosthidden]
    [default_interface]
    runtimeclass TabbedCommandBar : Microsoft.UI.Xaml.Controls.NavigationView
    {
        TabbedCommandBar();
    }
}
