namespace XamlToolkit.WinUI.Controls
{
	[webhosthidden]
	runtimeclass MetadataItem
	{
		MetadataItem();

		[noexcept]
		String Label;

		[noexcept]
		String AccessibleLabel;

		[noexcept]
		Microsoft.UI.Xaml.Input.ICommand Command;

		[noexcept]
		Object CommandParameter;
	};
}
