namespace XamlToolkit.WinUI.Controls
{
    runtimeclass InterspersedObservableVector : IObservableVector<Object>
    {
        InterspersedObservableVector(Object source);

        IVector<Object> ItemsSource();

        void Insert(UInt32 index, Object value);
    }
}
