namespace XamlToolkit.WinUI.Controls
{
    [webhosthidden]
    runtimeclass InterspersedObservableVector : IObservableVector<Object>
    {
        InterspersedObservableVector(Object source);

        [noexcept]
        IVector<Object> ItemsSource();

        void Insert(UInt32 index, Object value);
    }
}
