namespace XamlToolkit.WinUI.Controls
{
    [webhosthidden]
    runtimeclass InterspersedObservableVector : [default] IObservableVector<Object>
    {
        [noexcept]
        IVector<Object> ItemsSource();

        void Insert(UInt32 index, Object value);

        void RemoveItem(Object value);
    }
}
