namespace XamlToolkit.WinUI.Controls
{
	[webhosthidden]
	interface ITokenStringContainer
	{
		String Text;

		Boolean IsLast{ get; };
	}

	[webhosthidden]
	[default_interface]
	runtimeclass PretokenStringContainer : Microsoft.UI.Xaml.DependencyObject, Windows.Foundation.IStringable, ITokenStringContainer
	{

	}
}
