namespace XamlToolkit.WinUI.Controls
{
    runtimeclass TokenItemAddingEventArgs 
    {
        TokenItemAddingEventArgs();

        TokenItemAddingEventArgs(String token);

        String TokenText;

        Object Item;

        Windows.Foundation.Deferral GetDeferral();

        Boolean Cancel;
    }
}
