import "TokenizingTextBox/TokenizingTextBoxItem.idl";

namespace XamlToolkit.WinUI.Controls
{
    [webhosthidden]
    runtimeclass TokenItemRemovingEventArgs
    {
        TokenItemRemovingEventArgs();

        TokenItemRemovingEventArgs(Object item, TokenizingTextBoxItem token);

        Windows.Foundation.Deferral GetDeferral();

        [noexcept]
        Object Item{ get; };

        [noexcept]
        TokenizingTextBoxItem Token{ get; };

        [noexcept]
        Boolean Cancel;
    }
}
