import "TokenizingTextBox/TokenItemAddingEventArgs.idl";
import "TokenizingTextBox/TokenItemRemovingEventArgs.idl";

namespace XamlToolkit.WinUI.Controls
{
    [webhosthidden]
    runtimeclass TokenizingTextBox : Microsoft.UI.Xaml.Controls.ListViewBase
    {
        TokenizingTextBox();

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty AutoSuggestBoxStyleProperty{ get; };

        Microsoft.UI.Xaml.Style AutoSuggestBoxStyle;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty AutoSuggestBoxTextBoxStyleProperty{ get; };

        Microsoft.UI.Xaml.Style AutoSuggestBoxTextBoxStyle;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TextMemberPathProperty{ get; };

        String TextMemberPath;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TokenItemTemplateProperty{ get; };

        Microsoft.UI.Xaml.DataTemplate TokenItemTemplate;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TokenItemTemplateSelectorProperty{ get; };

        Microsoft.UI.Xaml.Controls.DataTemplateSelector TokenItemTemplateSelector;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TokenDelimiterProperty{ get; };

        String TokenDelimiter;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TokenSpacingProperty{ get; };

        Double TokenSpacing;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty PlaceholderTextProperty{ get; };

        String PlaceholderText;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty QueryIconProperty{ get; };

        Microsoft.UI.Xaml.Controls.IconSource QueryIcon;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TextProperty{ get; };

        String Text;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty SuggestedItemsSourceProperty{ get; };

        Object SuggestedItemsSource;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty SuggestedItemTemplateProperty{ get; };

        Microsoft.UI.Xaml.DataTemplate SuggestedItemTemplate;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty SuggestedItemTemplateSelectorProperty{ get; };

        Microsoft.UI.Xaml.Controls.DataTemplateSelector SuggestedItemTemplateSelector;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty SuggestedItemContainerStyleProperty{ get; };

        Microsoft.UI.Xaml.Style SuggestedItemContainerStyle;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TabNavigateBackOnArrowProperty{ get; };

        Boolean TabNavigateBackOnArrow;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty MaximumTokensProperty{ get; };

        Int32 MaximumTokens;

        event Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Controls.AutoSuggestBox, Microsoft.UI.Xaml.Controls.AutoSuggestBoxTextChangedEventArgs> TextChanged;

        event Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Controls.AutoSuggestBox, Microsoft.UI.Xaml.Controls.AutoSuggestBoxSuggestionChosenEventArgs> SuggestionChosen;

        event Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Controls.AutoSuggestBox, Microsoft.UI.Xaml.Controls.AutoSuggestBoxQuerySubmittedEventArgs> QuerySubmitted;

        event Windows.Foundation.TypedEventHandler<TokenizingTextBox, TokenItemAddingEventArgs> TokenItemAdding;

        event Windows.Foundation.TypedEventHandler<TokenizingTextBox, Object> TokenItemAdded;

        event Windows.Foundation.TypedEventHandler<TokenizingTextBox, TokenItemRemovingEventArgs> TokenItemRemoving;

        event Windows.Foundation.TypedEventHandler<TokenizingTextBox, Object> TokenItemRemoved;
    }
}
