namespace XamlToolkit.WinUI.Controls
{
    runtimeclass TokenizingTextBoxStyleSelector : Microsoft.UI.Xaml.Controls.StyleSelector
    {
        TokenizingTextBoxStyleSelector();

        [noexcept]
        Microsoft.UI.Xaml.Style TokenStyle;

        [noexcept]
        Microsoft.UI.Xaml.Style TextStyle;
    }
}
