namespace XamlToolkit.WinUI.Controls
{
    runtimeclass TokenizingTextBoxStyleSelector : Microsoft.UI.Xaml.Controls.StyleSelector
    {
        TokenizingTextBoxStyleSelector();

        Microsoft.UI.Xaml.Style TokenStyle;

        Microsoft.UI.Xaml.Style TextStyle;
    }
}
