import "TokenizingTextBox/TokenizingTextBoxItem.idl";

namespace XamlToolkit.WinUI.Controls
{
    runtimeclass TokenItemRemovingEventArgs
    {
        TokenItemRemovingEventArgs();

        TokenItemRemovingEventArgs(Object item, TokenizingTextBoxItem token);

        Object Item{ get; };

        TokenizingTextBoxItem Token{ get; };

        Windows.Foundation.Deferral GetDeferral();

        Boolean Cancel;
    }
}
