namespace XamlToolkit.WinUI.Controls
{
    [webhosthidden]
    runtimeclass TokenItemAddingEventArgs 
    {
        TokenItemAddingEventArgs();

        TokenItemAddingEventArgs(String token);

        Windows.Foundation.Deferral GetDeferral();

        [noexcept]
        String TokenText;

        [noexcept]
        Object Item;

        [noexcept]
        Boolean Cancel;
    }
}
