namespace XamlToolkit.WinUI.Behaviors
{
    /// <summary>
    /// Performs an fade animation on a ListView or GridView Header using composition.
    /// </summary>
    [webhosthidden]
    runtimeclass FadeHeaderBehavior : Microsoft.UI.Xaml.DependencyObject, [default] XamlToolkit.WinUI.Interactivity.IBehavior
    {
        FadeHeaderBehavior();
    }
}
