namespace XamlToolkit.WinUI.Behaviors
{
    /// <summary>
    /// Performs an animation on a ListView or GridView Header to make it 'sticky' and remain in view using composition.
    /// </summary>
    [webhosthidden]
    runtimeclass StickyHeaderBehavior : Microsoft.UI.Xaml.DependencyObject, XamlToolkit.WinUI.Interactivity.IBehavior
    {
        StickyHeaderBehavior();

        /// <summary>
        /// Show the header
        /// </summary>
        void Show();
    }
}
