namespace CommunityToolkit.WinUI.Controls
{
    [bindable]
    [default_interface]
	runtimeclass MetadataItem
	{
		MetadataItem();

		String Label;

		String AccessibleLabel;

		Microsoft.UI.Xaml.Input.ICommand Command;

		Object CommandParameter;
	};
}
