namespace XamlToolkit.Labs.WinUI
{
    enum WrapPanelItemsStretch
    {
        None,
        First,
        Last,
        Equal,
        Proportional,
    };

    enum WrapPanelItemsJustification
    {
        Automatic,
        Start,
        Center,
        End,
        SpaceAround,
        SpaceBetween,
        SpaceEvenly,
    };

    [webhosthidden]
    runtimeclass WrapPanel2 : Microsoft.UI.Xaml.Controls.Panel
    {
        WrapPanel2();

        Microsoft.UI.Xaml.Controls.Orientation Orientation;

        Double ItemSpacing;

        Double LineSpacing;

        WrapPanelItemsJustification ItemsJustification;

        WrapPanelItemsStretch ItemsStretch;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty OrientationProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ItemSpacingProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty LineSpacingProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ItemsJustificationProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ItemsStretchProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty LayoutLengthProperty{ get; };

        static Microsoft.UI.Xaml.GridLength GetLayoutLength(Microsoft.UI.Xaml.FrameworkElement obj);

        static void SetLayoutLength(Microsoft.UI.Xaml.FrameworkElement obj, Microsoft.UI.Xaml.GridLength value);
    }
}
