import "Xaml/AnimationSet.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A collection of animations that can be defined from XAML.
    /// </summary>
    [webhosthidden]
    [default_interface]
    runtimeclass AnimationDictionary : Microsoft.UI.Xaml.DependencyObject, Windows.Foundation.Collections.IVector<AnimationSet>
    {
        /// <summary>
        /// Initializes a new instance of the AnimationDictionary class.
        /// </summary>
        AnimationDictionary();
    }
}
