namespace XamlToolkit.Labs.WinUI
{
    [webhosthidden]
    interface ICanvasLayoutItem
    {
        Int32 Left;

        Int32 Top;

        Int32 Width;

        Int32 Height;

        Boolean IsInView;
    }

    [webhosthidden]
    [default_interface]
    runtimeclass CanvasLayout : Microsoft.UI.Xaml.Controls.VirtualizingLayout
    {
        CanvasLayout();
    }
}
