import "Xaml/KeyFrames/ScalarKeyFrame.idl";
import "Xaml/Abstract/Animation.idl";
import "Enums/FrameworkLayer.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A custom scalar animation.
    /// </summary>
    [webhosthidden]
    [contentproperty("KeyFrames")]
    runtimeclass ScalarAnimation : Animation
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScalarAnimation"/> class.
        /// </summary>
        ScalarAnimation();

        /// <summary>
        /// Gets or sets the implicit trigger target property name.
        /// </summary>
        [noexcept]
        String ImplicitTarget;

        /// <summary>
        /// Gets or sets the final value for the animation.
        /// </summary>
        Windows.Foundation.IReference<Double> To;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ToProperty{ get; };

        /// <summary>
        /// Gets or sets the optional starting value for the animation.
        /// </summary>
        Windows.Foundation.IReference<Double> From;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty FromProperty{ get; };

        /// <summary>
        /// Gets or sets the target property for the animation.
        /// </summary>
        String Target;

        /// <summary>
        /// Gets or sets the target framework layer for the animation.
        /// </summary>
        FrameworkLayer Layer;

        /// <summary>
        /// Gets or sets the optional keyframe collection for the current animation.
        /// </summary>
        Windows.Foundation.Collections.IVector<ScalarKeyFrame> KeyFrames;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty KeyFramesProperty{ get; };
    }
}



