import "SwitchPresenter/CaseCollection.idl";

namespace XamlToolkit.WinUI.Controls
{
	[contentproperty("SwitchCases")]
	runtimeclass SwitchConverter : Microsoft.UI.Xaml.DependencyObject, Microsoft.UI.Xaml.Data.IValueConverter
	{
		SwitchConverter();

		CaseCollection SwitchCases;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty SwitchCasesProperty{ get; };

		/*Windows.Foundation.IReference<Windows.UI.Xaml.Interop.TypeName> TargetType;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty TargetTypeProperty{ get; };*/
	}
}
