namespace XamlToolkit.WinUI.Controls
{
    [webhosthidden]
    runtimeclass SuggestionChosenEventArgs 
    {
        SuggestionChosenEventArgs();

        [noexcept]
        String QueryText{ get; };

        [noexcept]
        String Prefix{ get; };

        [noexcept]
        String DisplayText{ get; set; };

        [noexcept]
        Object SelectedItem{ get; };

        [noexcept]
        Guid Id{ get; };

        [noexcept]
        Microsoft.UI.Text.ITextCharacterFormat Format;

        Windows.Foundation.Deferral GetDeferral();
    }
}
