namespace XamlToolkit.WinUI.Controls
{
    runtimeclass SuggestionRequestedEventArgs 
    {
        SuggestionRequestedEventArgs();

        String Prefix;

        String QueryText;

        Boolean Cancel;

        Windows.Foundation.Deferral GetDeferral();
    }
}
