<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
		<UseWinUI>true</UseWinUI>
		<AssetTargetFallback>$(AssetTargetFallback);native</AssetTargetFallback>
		<Win2DWarnNoPlatform>false</Win2DWarnNoPlatform>
		<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
	</PropertyGroup>

	<PropertyGroup>
		<CsWinRTIncludes>XamlToolkit.WinUI.Media</CsWinRTIncludes>
	</PropertyGroup>

	<ItemGroup>
		<CsWinRTInputs Include="$(Win2DWinMDPath)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.CsWinRT" />
		<PackageReference Include="Microsoft.WindowsAppSDK.WinUI" />
		<PackageReference Include="Microsoft.Graphics.Win2D" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\XamlToolkit.WinUI.Media\XamlToolkit.WinUI.Media.vcxproj" />
		<ProjectReference Include="..\XamlToolkit.WinUI\XamlToolkit.WinUI.Interop.csproj" />
		<ProjectReference Include="..\XamlToolkit.WinUI.Animations\XamlToolkit.WinUI.Animations.Interop.csproj" />
	</ItemGroup>
</Project>