import "Xaml/Abstract/Animation.idl";
import "Xaml/KeyFrames/Vector3KeyFrame.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A center point animation working on the composition layer.
    /// </summary>
    [contentproperty("KeyFrames")]
    runtimeclass CenterPointAnimation : Animation
    {
        CenterPointAnimation();

        /// <summary>
        /// Gets or sets the implicit trigger target property name.
        /// </summary>
        [noexcept]
        String ImplicitTarget; 

        String To;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ToProperty{ get; };

        String From;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty FromProperty{ get; };

        /// <summary>
        /// Gets or sets the optional keyframe collection for the current animation.
        /// </summary>
        Windows.Foundation.Collections.IVector<Vector3KeyFrame> KeyFrames;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty KeyFramesProperty{ get; };
    }
}
