import "Xaml/Abstract/Animation.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A clip animation working on the composition layer.
    /// </summary>
    [webhosthidden]
    runtimeclass ClipAnimation : Animation
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClipAnimation"/> class.
        /// </summary>
        ClipAnimation();

        /// <summary>
        /// Gets or sets the final value for the animation.
        /// </summary>
        Windows.Foundation.IReference<Microsoft.UI.Xaml.Thickness> To;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ToProperty{ get; };

        /// <summary>
        /// Gets or sets the optional starting value for the animation.
        /// </summary>
        Windows.Foundation.IReference<Microsoft.UI.Xaml.Thickness> From;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty FromProperty{ get; };
    }
}

