import "Xaml/Abstract/Animation.idl";
import "Xaml/KeyFrames/ScalarKeyFrame.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A rotation in degrees animation working on the composition layer.
    /// </summary>
    [contentproperty("KeyFrames")]
    runtimeclass RotationInDegreesAnimation : Animation
    {
        RotationInDegreesAnimation();

        /// <summary>
        /// Gets or sets the implicit trigger target property name.
        /// </summary>
        [noexcept]
        String ImplicitTarget;

        /// <summary>
        /// Gets or sets the final value for the animation.
        /// </summary>
        Windows.Foundation.IReference<Double> To;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ToProperty{ get; };

        /// <summary>
        /// Gets or sets the optional starting value for the animation.
        /// </summary>
        Windows.Foundation.IReference<Double> From;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty FromProperty{ get; };

        /// <summary>
        /// Gets or sets the optional keyframe collection for the current animation.
        /// </summary>
        Windows.Foundation.Collections.IVector<ScalarKeyFrame> KeyFrames;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty KeyFramesProperty{ get; };
    }
}
