import "Xaml/Abstract/Animation.idl";
import "Xaml/KeyFrames/Vector3KeyFrame.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A translation animation working on the composition layer.
    /// </summary>
    [contentproperty("KeyFrames")]
    runtimeclass TranslationAnimation : Animation
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TranslationAnimation"/> class.
        /// </summary>
        TranslationAnimation();

        /// <summary>
        /// Gets or sets the implicit trigger target property name.
        /// </summary>
        [noexcept]
        String ImplicitTarget;

        /// <summary>
        /// Gets or sets the final value for the animation.
        /// </summary>
        String To;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty ToProperty{ get; };

        /// <summary>
        /// Gets or sets the optional starting value for the animation.
        /// </summary>
        String From;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty FromProperty{ get; };

        /// <summary>
        /// Gets or sets the optional keyframe collection for the current animation.
        /// </summary>
        Windows.Foundation.Collections.IVector<Vector3KeyFrame> KeyFrames;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty KeyFramesProperty{ get; };
    }
}
