namespace XamlToolkit.Labs.WinUI
{
	[webhosthidden]
	runtimeclass DataTable : Microsoft.UI.Xaml.Controls.Panel
    {
        DataTable();

        Double ColumnSpacing;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ColumnSpacingProperty{ get; };
    }
}
