namespace XamlToolkit.Labs.WinUI
{
	runtimeclass DataTable : Microsoft.UI.Xaml.Controls.Panel
	{
		DataTable();

		Double ColumnSpacing;

		static Microsoft.UI.Xaml.DependencyProperty ColumnSpacingProperty{ get; };
	}
}
