namespace XamlToolkit.WinUI.Controls
{
    enum StaggeredLayoutItemsStretch
    {
        None,
        Fill
    };

    [webhosthidden]
    runtimeclass StaggeredLayout : Microsoft.UI.Xaml.Controls.VirtualizingLayout
    {
        StaggeredLayout();

        StaggeredLayoutItemsStretch ItemsStretch;
        Double DesiredColumnWidth;
        Double ColumnSpacing;
        Double RowSpacing;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty DesiredColumnWidthProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ColumnSpacingProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty RowSpacingProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ItemsStretchProperty{ get; };
    }
}
