import "Extensions/Markup/TextIconExtension.idl";

namespace CommunityToolkit.WinUI
{
    [default_interface]
    runtimeclass SymbolIconExtension : TextIconExtension
    {
        SymbolIconExtension();

        Microsoft.UI.Xaml.Controls.Symbol Symbol;
    }
}
