// Wrapper for the XAML-generated XamlTypeInfo.g.cpp.
#include "pch.h"
#include "winrt_module_imports.h"

#include "Adorners/Adorner.h"
#include "Adorners/AdornerDecorator.h"
#include "Adorners/AdornerLayer.h"
#include "Adorners/ResizeElement/ResizeElementAdorner.h"
#include "Adorners/ResizeElement/Thumb/ResizeThumb.h"
#include "CanvasLayout/CanvasLayout.h"
#include "ColorAnalyzer/ColorExtensions.h"
#include "ColorAnalyzer/ColorPaletteSampler/ColorPaletteSampler.h"
#include "ColorAnalyzer/ColorSources/ColorSource.h"
#include "ColorAnalyzer/ColorSources/StreamColorSource.h"
#include "ColorAnalyzer/ColorSources/UIColorSource.h"
#include "ColorAnalyzer/ColorSources/UrlColorSource.h"
#include "ColorAnalyzer/ContrastHelper/ContrastHelper.h"
#include "ColorAnalyzer/PaletteSelectors/AccentColorPaletteSelector.h"
#include "ColorAnalyzer/PaletteSelectors/BaseColorPaletteSelector.h"
#include "ColorAnalyzer/PaletteSelectors/ColorPaletteSelector.h"
#include "ColorAnalyzer/PaletteSelectors/ColorWeightPaletteSelector.h"
#include "DataTable/DataColumn.h"
#include "DataTable/DataRow.h"
#include "DataTable/DataTable.h"
#include "MarkdownTextBlock/MarkdownConfig.h"
#include "MarkdownTextBlock/MarkdownTextBlock.h"
#include "MarkdownTextBlock/MarkdownThemes.h"
#include "MarkdownTextBlock/TextElements/MdTableUIElement.h"
#include "Marquee/Marquee.h"
#include "OpacityMaskView/OpacityMaskView.h"
#include "Ribbon/DoubleVector.h"
#include "Ribbon/Ribbon.h"
#include "Ribbon/RibbonCollapsibleGroup.h"
#include "Ribbon/RibbonGroup.h"
#include "Ribbon/RibbonPanel.h"
#include "Shimmer/Shimmer.h"
#include "TokenView/TokenItem.h"
#include "TokenView/TokenItemRemovingEventArgs.h"
#include "TokenView/TokenView.h"
#include "WrapPanel2/WrapPanel2.h"

#if __has_include("Generated Files\\XamlTypeInfo.g.cpp")
#include "Generated Files\\XamlTypeInfo.g.cpp"
#endif