import "TokenVIew/TokenItemRemovingEventArgs.idl";

namespace XamlToolkit.Labs.WinUI
{
    unsealed runtimeclass TokenItem : Microsoft.UI.Xaml.Controls.ListViewItem
    {
        TokenItem();

        Boolean IsRemoveable;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty IsRemoveableProperty{ get; };

        Microsoft.UI.Xaml.Controls.IconElement Icon;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty IconProperty{ get; };

        event Windows.Foundation.EventHandler<TokenItemRemovingEventArgs> Removing;

        overridable void OnIconPropertyChanged(Microsoft.UI.Xaml.Controls.IconElement oldValue, Microsoft.UI.Xaml.Controls.IconElement newValue);
    }
}
