import "TokenVIew/TokenItem.idl";

namespace XamlToolkit.Labs.WinUI
{
    runtimeclass TokenItemRemovingEventArgs 
    {
        TokenItemRemovingEventArgs();

        TokenItemRemovingEventArgs(Object item, TokenItem tokenItem);

        [noexcept]
        Object Item{ get; };

        [noexcept]
        TokenItem TokenItem{ get; };
    }
}
