namespace XamlToolkit.WinUI
{
    runtimeclass BitmapIconExtension : Microsoft.UI.Xaml.Markup.MarkupExtension
    {
        BitmapIconExtension();

        Windows.Foundation.Uri Source;

        Boolean ShowAsMonochrome;
    }
}
