namespace XamlToolkit.WinUI
{
    runtimeclass BitmapIconExtension : Microsoft.UI.Xaml.Markup.MarkupExtension
    {
        BitmapIconExtension();

        [noexcept]
        Windows.Foundation.Uri Source;

        [noexcept]
        Boolean ShowAsMonochrome;
    }
}
