import "Extensions/Markup/TextIconExtension.idl";

namespace XamlToolkit.WinUI
{
	[webhosthidden]
	runtimeclass FontIconExtension : TextIconExtension
    {
        FontIconExtension();

        [noexcept]
        String Glyph;

        [noexcept]
        Microsoft.UI.Xaml.Media.FontFamily FontFamily;
    }
}
