namespace XamlToolkit.WinUI
{
    /// <summary>
    /// Custom <see cref="MarkupExtension"/> which can provide nullable bool values.
    /// </summary>
    runtimeclass NullableBoolExtension : Microsoft.UI.Xaml.Markup.MarkupExtension
    {
        NullableBoolExtension();

        /// <summary>
        /// Gets or sets a value indicating whether the value of the Boolean is true.  Ignored if <see cref="IsNull"/> is true.
        /// </summary>
        Boolean Value;

        /// <summary>
        /// Gets or sets a value indicating whether the value should be null.  Overrides the <see cref="Value"/> property.
        /// </summary>
        Boolean IsNull;
    }
}
