import "Extensions/Markup/TextIconExtension.idl";

namespace XamlToolkit.WinUI
{
    runtimeclass SymbolIconExtension : TextIconExtension
    {
        SymbolIconExtension();

        Microsoft.UI.Xaml.Controls.Symbol Symbol;
    }
}
