import "Extensions/Markup/TextIconExtension.idl";

namespace XamlToolkit.WinUI
{
    [webhosthidden]
    runtimeclass SymbolIconExtension : TextIconExtension
    {
        SymbolIconExtension();

        [noexcept]
        Microsoft.UI.Xaml.Controls.Symbol Symbol;
    }
}
