import "Extensions/Markup/TextIconExtension.idl";

namespace XamlToolkit.WinUI
{
    runtimeclass SymbolIconSourceExtension : TextIconExtension
    {
        SymbolIconSourceExtension();

        Microsoft.UI.Xaml.Controls.Symbol Symbol;
    }
}
