import "SettingsControls/SettingsExpander/SettingsExpander.idl";

namespace XamlToolkit.WinUI.Controls
{
    runtimeclass SettingsExpanderAutomationPeer : Microsoft.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
    {
        SettingsExpanderAutomationPeer(XamlToolkit.WinUI.Controls.SettingsExpander owner);

        void RaiseExpandedChangedEvent(Boolean newValue);
    }
}
