// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

namespace XamlToolkit.WinUI.Media
{
    /// <summary>
    /// An enum used to modify the default placement of the input IGraphicsEffectSource instance in a blend operation
    /// </summary>
    enum Placement
    {
        /// <summary>
        /// The instance used to call the blend method is placed on top of the other
        /// </summary>
        Foreground = 0,

        /// <summary>
        /// The instance used to call the blend method is placed behind the other
        /// </summary>
        Background = 1,
    };
}
