import "Xaml/Interfaces/IActivity.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A base activity that can be added to an AnimationSet.
    /// </summary>
    unsealed runtimeclass Activity : Microsoft.UI.Xaml.DependencyObject, IActivity
    {
        Activity();

        /// <summary>
        /// Gets or sets the <see cref="TimeSpan"/> to wait before running the activity.
        /// </summary>
        Windows.Foundation.IReference<Windows.Foundation.TimeSpan> Delay;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty DelayProperty{ get; };
    }
}
