import "Xaml/Activities/Activity.idl";
import "Xaml/AnimationSet.idl";

namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// An IActivity which stops the provided AnimationSet when invoked.
    /// </summary>
    [webhosthidden]
    runtimeclass StopAnimationActivity : Activity
    {
        StopAnimationActivity();

        /// <summary>
        /// Gets or sets the linked AnimationSet instance to stop.
        /// </summary>
        AnimationSet Animation;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty AnimationProperty{ get; };

        /// <summary>
        /// Gets or sets the object to stop the specified animation for.
        /// If not specified, will use the current object the parent animation is running on.
        /// </summary>
        Microsoft.UI.Xaml.UIElement TargetObject;

		[noexcept]
		static Microsoft.UI.Xaml.DependencyProperty TargetObjectProperty{ get; };
    }
}
