namespace XamlToolkit.WinUI.Controls
{
    enum RangeSelectorProperty
    {
        MinimumValue,
        MaximumValue
    };

    runtimeclass RangeChangedEventArgs
    {
        RangeChangedEventArgs();

        [noexcept]
        Double OldValue{ get; };

        [noexcept]
        Double NewValue{ get; };

        [noexcept]
        RangeSelectorProperty ChangedRangeProperty{ get; };

        RangeChangedEventArgs(Double oldValue, Double newValue, RangeSelectorProperty changedRangeProperty);
    }
}

