import "RangeSelector/RangeChangedEventArgs.idl";

namespace XamlToolkit.WinUI.Controls
{
    [webhosthidden]
    runtimeclass RangeSelector : Microsoft.UI.Xaml.Controls.Control
    {
        RangeSelector();

        event Microsoft.UI.Xaml.Controls.Primitives.DragStartedEventHandler ThumbDragStarted;

        event Microsoft.UI.Xaml.Controls.Primitives.DragCompletedEventHandler ThumbDragCompleted;

        event Windows.Foundation.EventHandler<RangeChangedEventArgs> ValueChanged;

        Microsoft.UI.Xaml.DependencyProperty MinimumProperty{ get; };

        Microsoft.UI.Xaml.DependencyProperty MaximumProperty{ get; };

        Microsoft.UI.Xaml.DependencyProperty RangeStartProperty{ get; };

        Microsoft.UI.Xaml.DependencyProperty RangeEndProperty{ get; };

        Microsoft.UI.Xaml.DependencyProperty StepFrequencyProperty{ get; };

        Microsoft.UI.Xaml.DependencyProperty OrientationProperty{ get; };

        Double Minimum;

        Double Maximum;

        Double RangeStart;

        Double RangeEnd;

        Double StepFrequency;

        Microsoft.UI.Xaml.Controls.Orientation Orientation;
    }
}
