import "ColorAnalyzer/ColorSources/ColorSource.idl";
import "ColorAnalyzer/PaletteSelectors/ColorPaletteSelector.idl";

namespace XamlToolkit.Labs.WinUI
{
    [webhosthidden]
    [contentproperty("PaletteSelectors")]
    runtimeclass ColorPaletteSampler : Microsoft.UI.Xaml.DependencyObject
    {
        ColorPaletteSampler();

        void UpdatePalette();

		Windows.Foundation.IAsyncAction UpdatePaletteAsync();

        event Windows.Foundation.EventHandler<Object> PaletteUpdated;

        ColorSource Source;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty SourceProperty{ get; };

        [noexcept]
        Windows.Foundation.Collections.IVector<ColorPaletteSelector> PaletteSelectors;

        Windows.Foundation.Collections.IVectorView<PaletteColor> Palette{ get; };
    }
}
