namespace XamlToolkit.WinUI
{
    enum ConnectionState
    {
        Connected,
        Disconnected
    };

    runtimeclass NetworkConnectionStateTrigger : Microsoft.UI.Xaml.StateTriggerBase
    {
        NetworkConnectionStateTrigger();

        ConnectionState ConnectionState;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ConnectionStateProperty{ get; };
    }
}
