namespace XamlToolkit.WinUI
{
    enum RegexOptions
    {
        None,
        IgnoreCase,
        Multiline,
        Optimize
    };

    [webhosthidden]
    runtimeclass RegexStateTrigger : Microsoft.UI.Xaml.StateTriggerBase
    {
        RegexStateTrigger();

        String Value;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };

        String Expression;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ExpressionProperty{ get; };

        RegexOptions Options;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty OptionsProperty{ get; };
    }
}
