namespace XamlToolkit.WinUI
{
    runtimeclass UserHandPreferenceStateTrigger : Microsoft.UI.Xaml.StateTriggerBase
    {
        UserHandPreferenceStateTrigger();

        Windows.UI.ViewManagement.HandPreference HandPreference;

        static Microsoft.UI.Xaml.DependencyProperty HandPreferenceProperty{ get; };
    }
}
