import "IAction.idl";

namespace XamlToolkit.WinUI.Interactivity
{
    [webhosthidden]
    runtimeclass ChangeCustomPropertyAction : Microsoft.UI.Xaml.DependencyObject, XamlToolkit.WinUI.Interactivity.IAction
    {
        ChangeCustomPropertyAction();

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty PropertyNameProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TargetObjectProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };

        Microsoft.UI.Xaml.PropertyPath PropertyName;
        Object TargetObject;
        Object Value;
    }
}
