import "Trigger.idl";
import "Core/ComparisonConditionType.idl";

namespace XamlToolkit.WinUI.Interactivity
{
    [webhosthidden]
    runtimeclass DataTriggerBehavior : Trigger
    {
        DataTriggerBehavior();

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty BindingProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ComparisonConditionProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };

        Object Binding;
        XamlToolkit.WinUI.Interactivity.ComparisonConditionType ComparisonCondition;
        Object Value;
    }
}
