import "IAction.idl";

namespace XamlToolkit.WinUI.Interactivity
{
    runtimeclass GoToStateAction : Microsoft.UI.Xaml.DependencyObject, XamlToolkit.WinUI.Interactivity.IAction
    {
        GoToStateAction();

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty UseTransitionsProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty StateNameProperty{ get; };

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty TargetObjectProperty{ get; };

        Boolean UseTransitions;
        String StateName;
        Microsoft.UI.Xaml.FrameworkElement TargetObject;
    }
}
